#Declare the official Node runtime as parent image
FROM node:18

#set the working directory of the conatiner to /app
WORKDIR /app

# Install the ffmpeg into the container
RUN apt-get update && app-get install -y ffmpeg

#COpy the package.json and packaage-lock.json intot he working directory
COPY package*.json ./

# install any dependencies
RUN npm install

#Copy the contents of the app into the container
COPY . .

#Make sure that we have the port 3000 exposed
EXPOSE 3000

#Define the command to be used to run the app
CMD ["npm", "start"]

